### ISSUE TITLE
Ambreen Ali work to do for assignment 3 L1F16BSCS0196

### ISSUE THREAD

**Issue by MahrukhAsim** [MahrukhAsim/Assignment-3#1]
2. Connection to MySQL.
4. Form validation using ​regex on client side and server side 
We used forms on web pages to prompt for input from users in assignment 2. Forms are built up of various input components and posted to the server. All forms must be working, by using client-side and server-side validation, only valid data should be inserted into the database e.g. contact us, register, login, add products etc.

**Comment by ambreenali0196** [comment]
DONE
