### ISSUE TITLE
Faiqa Ali work to do for assignment 3 L1F16BSCS0200

### ISSUE THREAD

**Issue by MahrukhAsim** [MahrukhAsim/Assignment-3#2]
5. Includes & Templates 
When we are developing an application we want to minimize any repetition of the same task, for example having to copy and paste the page navigation menu and look and feel from one page to another. We can use PHP includes bringing in not only elements of a page, but commonly used functions and objects. Create a page template with a menu to link to each page you have created so far and include these templates into each page. You may need to edit the pages you have created previously to remove the header and footer tags that are now included in the template. 
  
6. CRUD – Read  
The first page we need to create is the main website homepage which lists all your posts according to your project. You will also need to create a suitable look and feel for these pages using a template method. You will need to read all the posts from your database and display them on this page.

**Comment by ambreenali0196** [comment]
MY WORK DONE
