### ISSUE TITLE
Usaid Khan work to do for assignment 3 L1F16BSCS0146

### ISSUE THREAD

**Issue by MahrukhAsim** [MahrukhAsim/Assignment-3#3]
7. CRUD – Create  
The second page we want to create is a page to allow you to start posting entries to your website according to your own project idea. You will need to store these entries in your database. 
  
8. CRUD – Update 
The next facility you will need is the ability to open an existing post and edit the content. Create a page that reads the information for the selected post into a form and then stores the changes back into the database. 
9. CRUD – Delete 
The final facility to your site is the ability to delete posts. You need a facility to select posts and delete it from the database. You should include a facility to prevent the admin user from deleting a post by accident.

**Comment by usaidsherwani** [comment]
Have been done
